version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 22c3683b094136c3
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db_config:/etc/mysql/conf.d
    ports:
      - "3306:3306"
